version: '3.0'
services:
  mysql:
    image: mysql:8
    environment:
      - TZ:Asia/Tokyo
    env_file:
      - ./credentials.env
    networks:
      - back
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./credentials.env:/docker-entrypoint-initdb.d/credentials.env
      - ./db/init_schema.sh:/docker-entrypoint-initdb.d/init_schema.sh
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always

  rails:
    build:
      context: .
      args:
        - RUBY_VERSION:2.4.1
        - RAILS_VERSION:5.1.2
        - NODE_VERSION:v8.1.3
        - GIT_REPOS:https://github.com/KeitaMoromizato/rails5.1-react-app.git
      dockerfile: Dockerfile
    networks:
      - front
      - back
    volumes:
      - ./rails5_app/:/web/rails5_app/:rw
      - web-sock:/web/rails5_app/tmp/sockets
      - web-assets:/web/rails5_app/public
    environment:
      - RAILS_ENV=development
      - MYSQL_HOST=mysql
      - TZ=Asia/Tokyo
    env_file:
      - ./credentials.env
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - web-sock:/web/rails5_app/tmp/sockets
      - web-assets:/web/rails5_app/public
      - ./nginx.conf:/etc/nginx/conf.d/rails.template
    environment:
      - APP_ROOT=/web/rails5_app
    command: /bin/bash -c "envsubst '$$APP_ROOT' < /etc/nginx/conf.d/rails.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - rails
    networks:
      - front

networks:
  front:
    external: false
  back:
    external: false

volumes:
  mysql-data:
    driver: local
    external: false
  web-assets:
    driver: local
    external: false
  web-sock:
    driver: local
    external: false
